### PR TITLE
#163218628 fix signup and login redirection to dashboard

### PR DESCRIPTION
**Pull request by wangonya**
#### What does this PR do?
Fixes navigation on [signup](https://wangonya.github.io/questioner/ui/signup/) and [login](https://wangonya.github.io/questioner/ui/login/) to redirect to dashboard instead of home page

#### Description of Task to be completed?
-[x] Fix signup and login redirection to dashboard

#### How should this be manually tested?
* Clone the gh-pages branch of the repo
* Open the `index.html` file in the ui folder

#### Any background context you want to provide?
* Backend not yet connected

#### What are the relevant pivotal tracker stories?
PT board [link](https://www.pivotaltracker.com/n/projects/2235158)
Story: `#163218628`

### CODE REVIEW

**Comment by jackiegitari1234** [comment]
I think you should include your repo link or maybe gh-pages link when explaining what the PR does

**Comment by jackiegitari1234** [comment]
PT link too

**Comment by wangonya** [comment]
Hey @jackiegitari1234, I've edited the comment to include the links. Thanks!

**Comment by betsybeth** [comment]
Good work

**Pull request merged**
