### PR TITLE
#163216403 fix wordings on pages

### PR DESCRIPTION
**Pull request by wangonya**
#### What does this PR do?
Replaces 'date' with actual dates on the meetups and replaces 'Author' with real (random placeholder) names on the question page.

#### Description of Task to be completed?
-[x] Replace 'date' with actual dates
-[x] Moves the date under the header
-[x] Replace 'Author' with names for clarity

#### How should this be manually tested?
* Clone the gh-pages branch of the repo
* Open the `index.html` file in the ui folder

#### Any background context you want to provide?
* Backend not yet connected

#### What are the relevant pivotal tracker stories?
`#163216403`

#### Screenshots
screenshot 2019-01-15 at 11 35 28
screenshot 2019-01-15 at 11 35 08

### CODE REVIEW

**Comment by betsybeth** [comment]
Good work

**Comment by betsybeth** [comment]
Add the redirections to the dashbord. I only see the dates

**Comment by wangonya** [comment]
> Add the redirections to the dashbord. I only see the dates

@betsybeth I'm opening a separate bug story for that. This one was specifically for fixing the wording.

**Comment by jackiegitari1234** [comment]
Awesome

**Pull request merged**
